/*
  File autogenerated by gengetopt version 2.22.2
  generated with the following command:
  gengetopt --input=cmdline.ggo --output-dir=. 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "This program is a Swiss army knife of file signature checksum tool\nthat can also identify and link duplicated files to save disk space.";

const char *gengetopt_args_info_usage = "Usage: checksum [options...] [input [output]]";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                Print help and exit",
  "  -V, --version             Print version and exit",
  "\nChecksum options:",
  "  ",
  "  -M, --method=sel          method/algorithm used to calculate the checksum  \n                              (default=`crc')",
  "\nInput/output options:",
  "  ",
  "  -f, --files               The rest of command line parameters are file names,\n                              compute checksum for each of them",
  "  -p, --pipe                file names provides from pipe (stdin)",
  "  -d, --directory=spec      operate recursively on directory given",
  "",
  "      --name=cachefile      name of the checksum cache file  \n                              (default=`.checksum.gz')",
  "  -z, --gzip=strength       gzip compression level to compress the checksum \n                              cache file  (default=`6')",
  "",
  "  -c, --check=sig           check against the signature, set exit status 0 = OK",
  "  -C, --compute=text        compute signature of text argument",
  "",
  "  -F, --format=string       format used for find -printf  (default=`%p\t%s')",
  "  -b, --bare                bare checksum output, don't output file name",
  "\nDuplication check options:",
  "  ",
  "  -D, --duplication         do duplication handling on the directory given by \n                              -d",
  "  -R, --relax               relax on file names, check different file names as \n                              well",
  "\nOther options:",
  "  ",
  "  -n, --dry-run             perform a trial run with no changes made",
  "  -v, --verbose             be verbose",
  "      --show-help           show the output of --help instead of generating \n                              code",
  "      --show-full-help      show the output of --full-help (i.e., including \n                              hidden options) instead of generating code",
  "      --show-detailed-help  show the output of --detailed-help (i.e., including \n                              details and hidden options) instead of generating \n                              code",
  "\nExamples:\n\n checksum -Mmd5 -f testf.?\n ls testf.? | checksum -Mcrc -p\n\nPlease refer to the info manual for further explanations.",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->method_given = 0 ;
  args_info->files_given = 0 ;
  args_info->pipe_given = 0 ;
  args_info->directory_given = 0 ;
  args_info->name_given = 0 ;
  args_info->gzip_given = 0 ;
  args_info->check_given = 0 ;
  args_info->compute_given = 0 ;
  args_info->format_given = 0 ;
  args_info->bare_given = 0 ;
  args_info->duplication_given = 0 ;
  args_info->relax_given = 0 ;
  args_info->dry_run_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->show_help_given = 0 ;
  args_info->show_full_help_given = 0 ;
  args_info->show_detailed_help_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->method_arg = gengetopt_strdup ("crc");
  args_info->method_orig = NULL;
  args_info->directory_arg = NULL;
  args_info->directory_orig = NULL;
  args_info->name_arg = gengetopt_strdup (".checksum.gz");
  args_info->name_orig = NULL;
  args_info->gzip_arg = gengetopt_strdup ("6");
  args_info->gzip_orig = NULL;
  args_info->check_arg = NULL;
  args_info->check_orig = NULL;
  args_info->compute_arg = NULL;
  args_info->compute_orig = NULL;
  args_info->format_arg = gengetopt_strdup ("%p\t%s");
  args_info->format_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->method_help = gengetopt_args_info_help[4] ;
  args_info->files_help = gengetopt_args_info_help[7] ;
  args_info->pipe_help = gengetopt_args_info_help[8] ;
  args_info->directory_help = gengetopt_args_info_help[9] ;
  args_info->name_help = gengetopt_args_info_help[11] ;
  args_info->gzip_help = gengetopt_args_info_help[12] ;
  args_info->check_help = gengetopt_args_info_help[14] ;
  args_info->compute_help = gengetopt_args_info_help[15] ;
  args_info->format_help = gengetopt_args_info_help[17] ;
  args_info->bare_help = gengetopt_args_info_help[18] ;
  args_info->duplication_help = gengetopt_args_info_help[21] ;
  args_info->relax_help = gengetopt_args_info_help[22] ;
  args_info->dry_run_help = gengetopt_args_info_help[25] ;
  args_info->verbose_help = gengetopt_args_info_help[26] ;
  args_info->verbose_min = 0;
  args_info->verbose_max = 0;
  args_info->show_help_help = gengetopt_args_info_help[27] ;
  args_info->show_full_help_help = gengetopt_args_info_help[28] ;
  args_info->show_detailed_help_help = gengetopt_args_info_help[29] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->method_arg));
  free_string_field (&(args_info->method_orig));
  free_string_field (&(args_info->directory_arg));
  free_string_field (&(args_info->directory_orig));
  free_string_field (&(args_info->name_arg));
  free_string_field (&(args_info->name_orig));
  free_string_field (&(args_info->gzip_arg));
  free_string_field (&(args_info->gzip_orig));
  free_string_field (&(args_info->check_arg));
  free_string_field (&(args_info->check_orig));
  free_string_field (&(args_info->compute_arg));
  free_string_field (&(args_info->compute_orig));
  free_string_field (&(args_info->format_arg));
  free_string_field (&(args_info->format_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->method_given)
    write_into_file(outfile, "method", args_info->method_orig, 0);
  if (args_info->files_given)
    write_into_file(outfile, "files", 0, 0 );
  if (args_info->pipe_given)
    write_into_file(outfile, "pipe", 0, 0 );
  if (args_info->directory_given)
    write_into_file(outfile, "directory", args_info->directory_orig, 0);
  if (args_info->name_given)
    write_into_file(outfile, "name", args_info->name_orig, 0);
  if (args_info->gzip_given)
    write_into_file(outfile, "gzip", args_info->gzip_orig, 0);
  if (args_info->check_given)
    write_into_file(outfile, "check", args_info->check_orig, 0);
  if (args_info->compute_given)
    write_into_file(outfile, "compute", args_info->compute_orig, 0);
  if (args_info->format_given)
    write_into_file(outfile, "format", args_info->format_orig, 0);
  if (args_info->bare_given)
    write_into_file(outfile, "bare", 0, 0 );
  if (args_info->duplication_given)
    write_into_file(outfile, "duplication", 0, 0 );
  if (args_info->relax_given)
    write_into_file(outfile, "relax", 0, 0 );
  if (args_info->dry_run_given)
    write_into_file(outfile, "dry-run", 0, 0 );
  write_multiple_into_file(outfile, args_info->verbose_given, "verbose", 0, 0);
  if (args_info->show_help_given)
    write_into_file(outfile, "show-help", 0, 0 );
  if (args_info->show_full_help_given)
    write_into_file(outfile, "show-full-help", 0, 0 );
  if (args_info->show_detailed_help_given)
    write_into_file(outfile, "show-detailed-help", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  FIX_UNUSED (additional_error);
  int error = 0;

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->verbose_given, args_info->verbose_min, args_info->verbose_max, "'--verbose' ('-v')"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  FIX_UNUSED (field);
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "method",	1, NULL, 'M' },
        { "files",	0, NULL, 'f' },
        { "pipe",	0, NULL, 'p' },
        { "directory",	1, NULL, 'd' },
        { "name",	1, NULL, 0 },
        { "gzip",	1, NULL, 'z' },
        { "check",	1, NULL, 'c' },
        { "compute",	1, NULL, 'C' },
        { "format",	1, NULL, 'F' },
        { "bare",	0, NULL, 'b' },
        { "duplication",	0, NULL, 'D' },
        { "relax",	0, NULL, 'R' },
        { "dry-run",	0, NULL, 'n' },
        { "verbose",	0, NULL, 'v' },
        { "show-help",	0, NULL, 0 },
        { "show-full-help",	0, NULL, 0 },
        { "show-detailed-help",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVM:fpd:z:c:C:F:bDRnv", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'M':	/* method/algorithm used to calculate the checksum.  */
        
        
          if (update_arg( (void *)&(args_info->method_arg), 
               &(args_info->method_orig), &(args_info->method_given),
              &(local_args_info.method_given), optarg, 0, "crc", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "method", 'M',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* The rest of command line parameters are file names,\ncompute checksum for each of them.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->files_given),
              &(local_args_info.files_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "files", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* file names provides from pipe (stdin).  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->pipe_given),
              &(local_args_info.pipe_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "pipe", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* operate recursively on directory given.  */
        
        
          if (update_arg( (void *)&(args_info->directory_arg), 
               &(args_info->directory_orig), &(args_info->directory_given),
              &(local_args_info.directory_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "directory", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'z':	/* gzip compression level to compress the checksum cache file.  */
        
        
          if (update_arg( (void *)&(args_info->gzip_arg), 
               &(args_info->gzip_orig), &(args_info->gzip_given),
              &(local_args_info.gzip_given), optarg, 0, "6", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "gzip", 'z',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* check against the signature, set exit status 0 = OK.  */
        
        
          if (update_arg( (void *)&(args_info->check_arg), 
               &(args_info->check_orig), &(args_info->check_given),
              &(local_args_info.check_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "check", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* compute signature of text argument.  */
        
        
          if (update_arg( (void *)&(args_info->compute_arg), 
               &(args_info->compute_orig), &(args_info->compute_given),
              &(local_args_info.compute_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "compute", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'F':	/* format used for find -printf.  */
        
        
          if (update_arg( (void *)&(args_info->format_arg), 
               &(args_info->format_orig), &(args_info->format_given),
              &(local_args_info.format_given), optarg, 0, "%p\t%s", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "format", 'F',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* bare checksum output, don't output file name.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->bare_given),
              &(local_args_info.bare_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "bare", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* do duplication handling on the directory given by -d.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->duplication_given),
              &(local_args_info.duplication_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "duplication", 'D',
              additional_error))
            goto failure;
        
          break;
        case 'R':	/* relax on file names, check different file names as well.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->relax_given),
              &(local_args_info.relax_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "relax", 'R',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* perform a trial run with no changes made.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->dry_run_given),
              &(local_args_info.dry_run_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "dry-run", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* be verbose.  */
        
          local_args_info.verbose_given++;
        
          break;

        case 0:	/* Long option with no short option */
          /* name of the checksum cache file.  */
          if (strcmp (long_options[option_index].name, "name") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->name_arg), 
                 &(args_info->name_orig), &(args_info->name_given),
                &(local_args_info.name_given), optarg, 0, ".checksum.gz", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "name", '-',
                additional_error))
              goto failure;
          
          }
          /* show the output of --help instead of generating code.  */
          else if (strcmp (long_options[option_index].name, "show-help") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->show_help_given),
                &(local_args_info.show_help_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "show-help", '-',
                additional_error))
              goto failure;
          
          }
          /* show the output of --full-help (i.e., including hidden options) instead of generating code.  */
          else if (strcmp (long_options[option_index].name, "show-full-help") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->show_full_help_given),
                &(local_args_info.show_full_help_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "show-full-help", '-',
                additional_error))
              goto failure;
          
          }
          /* show the output of --detailed-help (i.e., including details and hidden options) instead of generating code.  */
          else if (strcmp (long_options[option_index].name, "show-detailed-help") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->show_detailed_help_given),
                &(local_args_info.show_detailed_help_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "show-detailed-help", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  args_info->verbose_given += local_args_info.verbose_given;
  local_args_info.verbose_given = 0;
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
